In [2]:
import pandas as pd
from datetime import datetime

In [3]:
idx=pd.date_range("2018-01-01","2021-08-31")
행정동명=["건입동", "구좌읍", "남원읍", "노형동", "대륜동", "대정읍", "대천동", "도두동", "동홍동", 
      "봉개동", "삼도1동", "삼도2동", "삼양동", "서홍동", "성산읍", "송산동", "아라동", "안덕면",
      "애월읍", "연동", "영천동", "예래동", "오라동", "외도동", "용담1동", "용담2동", "우도면", 
      "이도1동", "이도2동", "이호동", "일도1동", "일도2동", "정방동", "조천읍", "중문동", "중앙동", 
      "천지동", "추자면", "표선면", "한경면", "한림읍", "화북동", "효돈동"]

행정시명=["제주시", "제주시", "서귀포시", "제주시", "서귀포시", "서귀포시", "서귀포시", "제주시", "서귀포시", 
      "제주시", "제주시", "제주시", "제주시", "서귀포시", "서귀포시", "서귀포시", "제주시", "서귀포시",
      "제주시", "제주시", "서귀포시", "서귀포시", "제주시", "제주시", "제주시", "제주시", "제주시", 
      "제주시", "제주시", "제주시", "제주시", "제주시", "서귀포시", "제주시", "서귀포시", "서귀포시", 
      "서귀포시", "제주시", "서귀포시", "제주시", "제주시", "제주시", "서귀포시"]
df_idx=[]
for i in range(len(idx)):
    for j in range(len(행정동명)):
        df_idx.append(idx[i])

In [4]:
df=pd.DataFrame(range(len(df_idx)))
df['날짜']=df_idx
df['연']=0
df['월']=0
df['행정시']=0
df['행정동']=0
df.drop(0, axis=1, inplace=True)
df

              날짜  연  월  행정시  행정동
0     2018-01-01  0  0    0    0
1     2018-01-01  0  0    0    0
2     2018-01-01  0  0    0    0
3     2018-01-01  0  0    0    0
4     2018-01-01  0  0    0    0
...          ... .. ..  ...  ...
57572 2021-08-31  0  0    0    0
57573 2021-08-31  0  0    0    0
57574 2021-08-31  0  0    0    0
57575 2021-08-31  0  0    0    0
57576 2021-08-31  0  0    0    0

[57577 rows x 5 columns]

In [5]:
for i in range(len(df_idx)):
    df.iloc[i, 1]=df_idx[i].year
    df.iloc[i, 2]=df_idx[i].month
    df.iloc[i, 3]=행정시명[i%len(행정시명)]
    df.iloc[i, 4]=행정동명[i%len(행정동명)]
df

              날짜     연  월   행정시  행정동
0     2018-01-01  2018  1   제주시  건입동
1     2018-01-01  2018  1   제주시  구좌읍
2     2018-01-01  2018  1  서귀포시  남원읍
3     2018-01-01  2018  1   제주시  노형동
4     2018-01-01  2018  1  서귀포시  대륜동
...          ...   ... ..   ...  ...
57572 2021-08-31  2021  8  서귀포시  표선면
57573 2021-08-31  2021  8   제주시  한경면
57574 2021-08-31  2021  8   제주시  한림읍
57575 2021-08-31  2021  8   제주시  화북동
57576 2021-08-31  2021  8  서귀포시  효돈동

[57577 rows x 5 columns]

In [6]:
행정동별_사업자수_df=pd.read_csv("전처리/행정동별_사업자수(2019).csv")
행정동별_사업자수_df

     행정시 행정구역명   사업체수
0    제주시   한림읍  2,521
1    제주시   애월읍  3,083
2    제주시   구좌읍  2,016
3    제주시   조천읍  2,319
4    제주시   한경면    899
5    제주시   추자면    224
6    제주시   우도면    312
7    제주시  일도1동  1,311
8    제주시  일도2동  2,625
9    제주시  이도1동  1,608
10   제주시  이도2동  5,666
11   제주시  삼도1동  1,452
12   제주시  삼도2동  1,076
13   제주시  용담1동    896
14   제주시  용담2동  1,418
15   제주시   건입동    849
16   제주시   화북동  1,947
17   제주시   삼양동  1,346
18   제주시   봉개동    348
19   제주시   아라동  2,369
20   제주시   오라동  1,182
21   제주시    연동  5,211
22   제주시   노형동  5,028
23   제주시   외도동  1,488
24   제주시   이호동    409
25   제주시   도두동  1,032
26  서귀포시   대정읍  2,016
27  서귀포시   남원읍  1,394
28  서귀포시   성산읍  1,841
29  서귀포시   안덕면  1,227
30  서귀포시   표선면  1,381
31  서귀포시   송산동    420
32  서귀포시   정방동    618
33  서귀포시   중앙동  1,286
34  서귀포시   천지동    728
35  서귀포시   효돈동    355
36  서귀포시   영천동    573
37  서귀포시   동홍동  1,908
38  서귀포시   서홍동    625
39  서귀포시   대륜동    964
40  서귀포시   대천동    696
41  서귀포시   중문동    936
42  서귀포시   예래동    495

In [7]:
df['사업체수']=0
df

              날짜     연  월   행정시  행정동  사업체수
0     2018-01-01  2018  1   제주시  건입동     0
1     2018-01-01  2018  1   제주시  구좌읍     0
2     2018-01-01  2018  1  서귀포시  남원읍     0
3     2018-01-01  2018  1   제주시  노형동     0
4     2018-01-01  2018  1  서귀포시  대륜동     0
...          ...   ... ..   ...  ...   ...
57572 2021-08-31  2021  8  서귀포시  표선면     0
57573 2021-08-31  2021  8   제주시  한경면     0
57574 2021-08-31  2021  8   제주시  한림읍     0
57575 2021-08-31  2021  8   제주시  화북동     0
57576 2021-08-31  2021  8  서귀포시  효돈동     0

[57577 rows x 6 columns]

In [8]:
for i in range(len(df)):
    for j in range(len(행정동별_사업자수_df)):
        if df.loc[i, '행정동']==행정동별_사업자수_df.loc[j,'행정구역명']:
            df.loc[i, '사업체수']= 행정동별_사업자수_df.loc[j,'사업체수']
df

              날짜     연  월   행정시  행정동   사업체수
0     2018-01-01  2018  1   제주시  건입동    849
1     2018-01-01  2018  1   제주시  구좌읍  2,016
2     2018-01-01  2018  1  서귀포시  남원읍  1,394
3     2018-01-01  2018  1   제주시  노형동  5,028
4     2018-01-01  2018  1  서귀포시  대륜동    964
...          ...   ... ..   ...  ...    ...
57572 2021-08-31  2021  8  서귀포시  표선면  1,381
57573 2021-08-31  2021  8   제주시  한경면    899
57574 2021-08-31  2021  8   제주시  한림읍  2,521
57575 2021-08-31  2021  8   제주시  화북동  1,947
57576 2021-08-31  2021  8  서귀포시  효돈동    355

[57577 rows x 6 columns]

In [9]:
월별_행정동별_세대수_df=pd.read_csv("전처리/월별_행정동별_세대수.csv", encoding="cp949")
월별_행정동별_세대수_df

,Unnamed: 0,행정구역명,기준일,총인구수,세대수,세대당 인구,남자 인구수,여자 인구수,남여 비율,기준월,기준년
0,0,건입동,2018-01-01,9800,4324,2.27,5085,4715,1.08,1,2018
1,1,건입동,2018-02-01,9814,4334,2.26,5090,4724,1.08,2,2018
2,2,건입동,2018-03-01,9783,4327,2.26,5072,4711,1.08,3,2018
3,3,건입동,2018-04-01,9788,4327,2.26,5070,4718,1.07,4,2018
4,4,건입동,2018-05-01,9800,4328,2.26,5070,4730,1.07,5,2018
...,...,...,...,...,...,...,...,...,...,...,...
1887,1887,효돈동,2021-04-01,5267,2318,2.27,2660,2607,1.02,4,2021
1888,1888,효돈동,2021-05-01,5266,2319,2.27,2661,2605,1.02,5,2021
1889,1889,효돈동,2021-06-01,5257,2316,2.27,2660,2597,1.02,6,2021
1890,1890,효돈동,2021-07-01,5272,2326,2.27,2665,2607,1.02,7,2021
1891,1891,효돈동,2021-08-01,5276,2324,2.27,2660,2616,1.02,8,2021

In [10]:
df['세대수']=0
df['세대당 인구']=0
df['남여 비율']=0
df

              날짜     연  월   행정시  행정동   사업체수  세대수  세대당 인구  남여 비율
0     2018-01-01  2018  1   제주시  건입동    849    0       0      0
1     2018-01-01  2018  1   제주시  구좌읍  2,016    0       0      0
2     2018-01-01  2018  1  서귀포시  남원읍  1,394    0       0      0
3     2018-01-01  2018  1   제주시  노형동  5,028    0       0      0
4     2018-01-01  2018  1  서귀포시  대륜동    964    0       0      0
...          ...   ... ..   ...  ...    ...  ...     ...    ...
57572 2021-08-31  2021  8  서귀포시  표선면  1,381    0       0      0
57573 2021-08-31  2021  8   제주시  한경면    899    0       0      0
57574 2021-08-31  2021  8   제주시  한림읍  2,521    0       0      0
57575 2021-08-31  2021  8   제주시  화북동  1,947    0       0      0
57576 2021-08-31  2021  8  서귀포시  효돈동    355    0       0      0

[57577 rows x 9 columns]

In [11]:
for i in range(len(df)):
    for j in range(len(월별_행정동별_세대수_df)):
        if df.loc[i, '월']==월별_행정동별_세대수_df.loc[j,'기준월'] and df.loc[i, '연']==월별_행정동별_세대수_df.loc[j,'기준년'] and df.loc[i, '행정동']==월별_행정동별_세대수_df.loc[j, '행정구역명']:
            df.loc[i, '세대수']= 월별_행정동별_세대수_df.loc[j,'세대수']
            df.loc[i, '세대당 인구']= 월별_행정동별_세대수_df.loc[j,'세대당 인구']
            df.loc[i, '남여 비율']= 월별_행정동별_세대수_df.loc[j,'남여 비율']
df

              날짜     연  월   행정시  행정동   사업체수    세대수  세대당 인구  남여 비율
0     2018-01-01  2018  1   제주시  건입동    849   4324    2.27   1.08
1     2018-01-01  2018  1   제주시  구좌읍  2,016   7493    2.08   1.05
2     2018-01-01  2018  1  서귀포시  남원읍  1,394   8345    2.29   1.05
3     2018-01-01  2018  1   제주시  노형동  5,028  20455    2.61   0.97
4     2018-01-01  2018  1  서귀포시  대륜동    964   5586    2.41   1.03
...          ...   ... ..   ...  ...    ...    ...     ...    ...
57572 2021-08-31  2021  8  서귀포시  표선면  1,381   6175    2.00   1.04
57573 2021-08-31  2021  8   제주시  한경면    899   4938    1.87   1.01
57574 2021-08-31  2021  8   제주시  한림읍  2,521  10546    2.01   1.06
57575 2021-08-31  2021  8   제주시  화북동  1,947   9691    2.50   0.99
57576 2021-08-31  2021  8  서귀포시  효돈동    355   2324    2.27   1.02

[57577 rows x 9 columns]

In [12]:
행정동별_주택종류_df=pd.read_csv("전처리/행정동별_주택종류.csv", encoding="cp949")
행정동별_주택종류_df

,행정구역명,단독주택,창고시설,제2종근린생활시설,제1종근린생활시설,공동주택,동.식물관련시설,숙박시설,교육연구시설,공장,...,야영장시설,소매점,판매및영업시설,공공용시설,장례시설,도축장,일반음식점,관광숙박시설,학원,공공업무시설
0,남원읍,5689,3846,438,482,101,468,169,29,56,...,0,0,0,0,1,0,0,0,0,0
1,대정읍,5382,1680,546,600,430,597,74,89,78,...,0,0,0,2,0,0,0,0,0,0
2,성산읍,4982,1604,566,571,126,423,244,40,41,...,4,0,0,0,0,0,0,0,0,0
3,안덕면,4272,1100,484,438,141,320,345,20,23,...,0,0,0,0,0,0,0,0,0,0
4,애월읍,4440,1081,407,287,120,372,148,49,44,...,3,1,1,0,0,0,0,0,1,0
5,표선면,3848,1325,472,492,90,467,125,48,52,...,0,0,0,0,0,0,0,0,0,0
6,구좌읍,4104,355,274,271,26,344,31,31,46,...,0,1,1,0,0,0,0,0,0,0
7,조천읍,3005,741,256,216,91,291,48,21,48,...,0,1,0,0,0,0,1,0,0,0
8,한림읍,1958,528,237,223,48,723,83,28,50,...,0,3,1,0,0,0,0,0,0,1
9,한경면,2680,630,138,141,10,197,4,20,8,...,0,0,0,0,0,0,0,1,0,0
10,중문동,1686,597,231,204,220,96,103,28,5,...,0,0,0,0,0,0,0,0,0,0
11,대륜동,1973,400,202,153,272,20,68,31,4,...,0,0,0,0,0,0,0,0,0,0
12,대천동,1882,593,145,146,185,14,82,11,9,...,0,0,0,0,0,0,0,0,0,0
13,영천동,1504,740,249,113,67,26,91,32,30,...,0,0,0,0,0,0,0,0,0,0
14,예래동,1198,473,139,133,40,50,176,12,4,...,0,0,0,0,0,0,0,0,0,0
15,동홍동,836,251,372,224,423,4,39,29,3,...,0,0,0,0,0,0,0,0,0,0
16,효돈동,1353,395,119,122,64,3,5,12,0,...,0,0,0,0,0,0,0,0,0,0
17,이도2동,1082,42,256,160,263,1,14,19,1,...,0,0,0,0,1,0,0,0,0,0
18,노형동,671,159,211,139,311,36,58,25,1,...,0,0,0,0,0,0,0,0,0,0
19,아라동,660,245,184,92,254,37,7,87,10,...,0,0,0,0,0,0,0,0,0,0
20,서홍동,853,243,162,108,196,18,2,12,0,...,0,0,0,0,0,0,0,0,0,0
21,일도2동,1111,9,95,90,122,2,6,6,0,...,0,0,0,0,0,0,0,0,0,0
22,송산동,882,136,108,107,49,6,62,7,5,...,0,0,0,0,0,0,0,0,0,0
23,연동,548,15,169,137,269,1,53,15,0,...,0,0,0,0,0,0,0,0,0,0
24,용담2동,629,21,95,64,58,2,8,8,1,...,0,0,0,0,0,0,0,0,0,0
25,천지동,518,28,126,132,33,0,60,4,1,...,0,0,0,0,0,0,0,0,0,0
26,중앙동,425,15,115,279,27,1,20,3,1,...,0,0,0,0,0,0,0,0,0,0
27,화북동,308,132,127,65,143,6,0,14,30,...,0,0,0,1,0,0,0,0,0,0
28,삼양동,377,165,76,49,128,4,0,2,3,...,0,0,0,0,0,0,0,0,0,0
29,오라동,337,71,113,62,131,8,7,16,2,...,0,0,0,0,0,0,0,0,0,0
30,외도동,313,101,107,64,118,8,2,8,2,...,0,0,0,0,0,0,0,0,0,0
31,정방동,372,6,108,116,20,0,44,2,3,...,0,0,0,0,0,0,0,0,0,0
32,삼도1동,485,5,41,58,46,0,21,2,0,...,0,0,0,0,0,0,0,0,0,0
33,추자면,550,14,23,54,1,4,0,0,7,...,0,1,0,1,0,1,0,0,0,0
34,우도면,470,60,43,63,1,3,8,3,3,...,0,0,0,0,1,0,0,0,0,0
35,봉개동,168,173,50,20,34,50,4,4,3,...,0,0,1,0,0,0,0,0,0,0
36,용담1동,290,3,36,46,37,0,5,5,2,...,0,0,0,0,0,0,0,0,0,0
37,건입동,219,24,41,55,50,0,11,1,5,...,0,0,1,0,0,0,0,0,0,0
38,이도1동,164,3,36,59,25,0,20,6,1,...,0,0,0,0,0,0,0,0,0,0
39,삼도2동,158,5,56,56,36,0,14,3,0,...,0,0,0,1,0,0,0,0,0,0
40,도두동,124,32,63,36,6,1,5,3,4,...,0,0,1,0,0,0,0,0,0,0
41,이호동,132,35,37,28,29,1,7,0,0,...,0,0,0,0,0,0,0,0,0,0
42,일도1동,69,3,31,70,8,0,8,0,0,...,0,0,0,0,0,0,0,0,0,0

In [13]:
행정동별_주택종류_df.columns

Index(['행정구역명', '단독주택', '창고시설', '제2종근린생활시설', '제1종근린생활시설', '공동주택', '동.식물관련시설',
       '숙박시설', '교육연구시설', '공장', '노유자시설', '문화및집회시설', '위험물저장및처리시설', '종교시설',
       '업무시설', '운동시설', '자동차관련시설', '관광휴게시설', '수련시설', '분뇨.쓰레기처리시설', '위락시설',
       '교정및군사시설', '발전시설', '근린생활시설', '방송통신시설', '자원순환관련시설', '교육연구및복지시설', '의료시설',
       '묘지관련시설', '판매시설', '운수시설', '축사', '야영장시설', '소매점', '판매및영업시설', '공공용시설',
       '장례시설', '도축장', '일반음식점', '관광숙박시설', '학원', '공공업무시설'],
      dtype='object')

In [14]:
df['단독주택']=0
df['창고시설']=0
df['제2종근린생활시설']=0
df['제1종근린생활시설']=0
df['공동주택']=0
df['동.식물관련시설']=0
df['숙박시설']=0
df['교육연구시설']=0
df['관광휴게시설']=0
df['분뇨.쓰레기처리시설']=0
df

,날짜,연,월,행정시,행정동,사업체수,세대수,세대당 인구,남여 비율,단독주택,창고시설,제2종근린생활시설,제1종근린생활시설,공동주택,동.식물관련시설,숙박시설,교육연구시설,관광휴게시설,분뇨.쓰레기처리시설
0,2018-01-01,2018,1,제주시,건입동,849,4324,2.27,1.08,0,0,0,0,0,0,0,0,0,0
1,2018-01-01,2018,1,제주시,구좌읍,"2,016",7493,2.08,1.05,0,0,0,0,0,0,0,0,0,0
2,2018-01-01,2018,1,서귀포시,남원읍,"1,394",8345,2.29,1.05,0,0,0,0,0,0,0,0,0,0
3,2018-01-01,2018,1,제주시,노형동,"5,028",20455,2.61,0.97,0,0,0,0,0,0,0,0,0,0
4,2018-01-01,2018,1,서귀포시,대륜동,964,5586,2.41,1.03,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57572,2021-08-31,2021,8,서귀포시,표선면,"1,381",6175,2.00,1.04,0,0,0,0,0,0,0,0,0,0
57573,2021-08-31,2021,8,제주시,한경면,899,4938,1.87,1.01,0,0,0,0,0,0,0,0,0,0
57574,2021-08-31,2021,8,제주시,한림읍,"2,521",10546,2.01,1.06,0,0,0,0,0,0,0,0,0,0
57575,2021-08-31,2021,8,제주시,화북동,"1,947",9691,2.50,0.99,0,0,0,0,0,0,0,0,0,0
57576,2021-08-31,2021,8,서귀포시,효돈동,355,2324,2.27,1.02,0,0,0,0,0,0,0,0,0,0

In [15]:
for i in range(len(df)):
    for j in range(len(행정동별_주택종류_df)):
        if df.loc[i, '행정동']==행정동별_주택종류_df.loc[j, '행정구역명']:
            df.loc[i, '단독주택']= 행정동별_주택종류_df.loc[j,'단독주택']
            df.loc[i, '공동주택']= 행정동별_주택종류_df.loc[j,'공동주택']
            df.loc[i, '창고시설']= 행정동별_주택종류_df.loc[j,'창고시설']
            df.loc[i, '제2종근린생활시설']= 행정동별_주택종류_df.loc[j,'제2종근린생활시설']
            df.loc[i, '제1종근린생활시설']= 행정동별_주택종류_df.loc[j,'제1종근린생활시설']
            df.loc[i, '동.식물관련시설']= 행정동별_주택종류_df.loc[j,'동.식물관련시설']
            df.loc[i, '숙박시설']= 행정동별_주택종류_df.loc[j,'숙박시설']
            df.loc[i, '교육연구시설']= 행정동별_주택종류_df.loc[j,'교육연구시설']
            df.loc[i, '관광휴게시설']= 행정동별_주택종류_df.loc[j,'관광휴게시설']
            df.loc[i, '분뇨.쓰레기처리시설']= 행정동별_주택종류_df.loc[j,'분뇨.쓰레기처리시설']
df

,날짜,연,월,행정시,행정동,사업체수,세대수,세대당 인구,남여 비율,단독주택,창고시설,제2종근린생활시설,제1종근린생활시설,공동주택,동.식물관련시설,숙박시설,교육연구시설,관광휴게시설,분뇨.쓰레기처리시설
0,2018-01-01,2018,1,제주시,건입동,849,4324,2.27,1.08,219,24,41,55,50,0,11,1,0,0
1,2018-01-01,2018,1,제주시,구좌읍,"2,016",7493,2.08,1.05,4104,355,274,271,26,344,31,31,0,3
2,2018-01-01,2018,1,서귀포시,남원읍,"1,394",8345,2.29,1.05,5689,3846,438,482,101,468,169,29,0,10
3,2018-01-01,2018,1,제주시,노형동,"5,028",20455,2.61,0.97,671,159,211,139,311,36,58,25,1,1
4,2018-01-01,2018,1,서귀포시,대륜동,964,5586,2.41,1.03,1973,400,202,153,272,20,68,31,0,5
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57572,2021-08-31,2021,8,서귀포시,표선면,"1,381",6175,2.00,1.04,3848,1325,472,492,90,467,125,48,1,9
57573,2021-08-31,2021,8,제주시,한경면,899,4938,1.87,1.01,2680,630,138,141,10,197,4,20,0,2
57574,2021-08-31,2021,8,제주시,한림읍,"2,521",10546,2.01,1.06,1958,528,237,223,48,723,83,28,6,15
57575,2021-08-31,2021,8,제주시,화북동,"1,947",9691,2.50,0.99,308,132,127,65,143,6,0,14,0,1
57576,2021-08-31,2021,8,서귀포시,효돈동,355,2324,2.27,1.02,1353,395,119,122,64,3,5,12,0,0

In [16]:
건설이후_df=pd.read_csv("전처리/행정동별_건설이후(일).csv", encoding="cp949")
건설이후_df

    Unnamed: 0  행정동명  건설이후(일)  건설이후(일)_std
0            0   건입동  10697.0       5011.0
1            1   구좌읍  14289.0       8577.0
2            2   남원읍   9737.0       5979.0
3            3   노형동   6155.0       4172.0
4            4   대륜동  10172.0       9211.0
5            5   대정읍  11412.0       9638.0
6            6   대천동   9923.0       7812.0
7            7   도두동   6555.0       4986.0
8            8   동홍동   8328.0       5572.0
9            9   봉개동   6970.0       4991.0
10          10  삼도1동  12132.0       3942.0
11          11  삼도2동  10721.0       4933.0
12          12   삼양동   6505.0       4948.0
13          13   서홍동   9939.0       7038.0
14          14   성산읍  10208.0       8505.0
15          15   송산동  13318.0       9322.0
16          16   아라동   5438.0       4793.0
17          17   안덕면   8958.0       8348.0
18          18   애월읍  10079.0       8184.0
19          19    연동   8798.0       4435.0
20          20   영천동   9537.0       7021.0
21          21   예래동   9882.0       7952.0
22          22   오라동   6637.0       5381.0
23          23   외도동   5967.0       4596.0
24          24  용담1동  12220.0       4756.0
25          25  용담2동  10316.0       4965.0
26          26   우도면  13150.0       7409.0
27          27  이도1동  12991.0       5075.0
28          28  이도2동   8364.0       4710.0
29          29   이호동   6610.0       4775.0
30          30  일도1동  12395.0       4939.0
31          31  일도2동  11429.0       4186.0
32          32   정방동  15604.0       8189.0
33          33   조천읍  11987.0      10018.0
34          34   중문동  10438.0       7858.0
35          35   중앙동  13604.0       4725.0
36          36   천지동  12682.0       5681.0
37          37   추자면  16672.0       6596.0
38          38   표선면   8906.0       7151.0
39          39   한경면  15084.0       9407.0
40          40   한림읍   9980.0       8644.0
41          41   화북동   8003.0       5578.0
42          42   효돈동  12578.0       8205.0

In [17]:
df['건설이후(일)']=0
df['건설이후(일)_std']=0
df

,날짜,연,월,행정시,행정동,사업체수,세대수,세대당 인구,남여 비율,단독주택,...,제2종근린생활시설,제1종근린생활시설,공동주택,동.식물관련시설,숙박시설,교육연구시설,관광휴게시설,분뇨.쓰레기처리시설,건설이후(일),건설이후(일)_std
0,2018-01-01,2018,1,제주시,건입동,849,4324,2.27,1.08,219,...,41,55,50,0,11,1,0,0,0,0
1,2018-01-01,2018,1,제주시,구좌읍,"2,016",7493,2.08,1.05,4104,...,274,271,26,344,31,31,0,3,0,0
2,2018-01-01,2018,1,서귀포시,남원읍,"1,394",8345,2.29,1.05,5689,...,438,482,101,468,169,29,0,10,0,0
3,2018-01-01,2018,1,제주시,노형동,"5,028",20455,2.61,0.97,671,...,211,139,311,36,58,25,1,1,0,0
4,2018-01-01,2018,1,서귀포시,대륜동,964,5586,2.41,1.03,1973,...,202,153,272,20,68,31,0,5,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57572,2021-08-31,2021,8,서귀포시,표선면,"1,381",6175,2.00,1.04,3848,...,472,492,90,467,125,48,1,9,0,0
57573,2021-08-31,2021,8,제주시,한경면,899,4938,1.87,1.01,2680,...,138,141,10,197,4,20,0,2,0,0
57574,2021-08-31,2021,8,제주시,한림읍,"2,521",10546,2.01,1.06,1958,...,237,223,48,723,83,28,6,15,0,0
57575,2021-08-31,2021,8,제주시,화북동,"1,947",9691,2.50,0.99,308,...,127,65,143,6,0,14,0,1,0,0
57576,2021-08-31,2021,8,서귀포시,효돈동,355,2324,2.27,1.02,1353,...,119,122,64,3,5,12,0,0,0,0

In [18]:
for i in range(len(df)):
    for j in range(len(건설이후_df)):
        if df.loc[i, '행정동']==건설이후_df.loc[j, '행정동명']:
            df.loc[i, '건설이후(일)']= 건설이후_df.loc[j,'건설이후(일)']
            df.loc[i, '건설이후(일)_std']= 건설이후_df.loc[j,'건설이후(일)_std']
df

,날짜,연,월,행정시,행정동,사업체수,세대수,세대당 인구,남여 비율,단독주택,...,제2종근린생활시설,제1종근린생활시설,공동주택,동.식물관련시설,숙박시설,교육연구시설,관광휴게시설,분뇨.쓰레기처리시설,건설이후(일),건설이후(일)_std
0,2018-01-01,2018,1,제주시,건입동,849,4324,2.27,1.08,219,...,41,55,50,0,11,1,0,0,10697.0,5011.0
1,2018-01-01,2018,1,제주시,구좌읍,"2,016",7493,2.08,1.05,4104,...,274,271,26,344,31,31,0,3,14289.0,8577.0
2,2018-01-01,2018,1,서귀포시,남원읍,"1,394",8345,2.29,1.05,5689,...,438,482,101,468,169,29,0,10,9737.0,5979.0
3,2018-01-01,2018,1,제주시,노형동,"5,028",20455,2.61,0.97,671,...,211,139,311,36,58,25,1,1,6155.0,4172.0
4,2018-01-01,2018,1,서귀포시,대륜동,964,5586,2.41,1.03,1973,...,202,153,272,20,68,31,0,5,10172.0,9211.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57572,2021-08-31,2021,8,서귀포시,표선면,"1,381",6175,2.00,1.04,3848,...,472,492,90,467,125,48,1,9,8906.0,7151.0
57573,2021-08-31,2021,8,제주시,한경면,899,4938,1.87,1.01,2680,...,138,141,10,197,4,20,0,2,15084.0,9407.0
57574,2021-08-31,2021,8,제주시,한림읍,"2,521",10546,2.01,1.06,1958,...,237,223,48,723,83,28,6,15,9980.0,8644.0
57575,2021-08-31,2021,8,제주시,화북동,"1,947",9691,2.50,0.99,308,...,127,65,143,6,0,14,0,1,8003.0,5578.0
57576,2021-08-31,2021,8,서귀포시,효돈동,355,2324,2.27,1.02,1353,...,119,122,64,3,5,12,0,0,12578.0,8205.0

In [19]:
행정동별_학교급수_df=pd.read_csv("전처리/행정동별_학교급수.csv", encoding="cp949")
행정동별_학교급수_df

    행정동명  고등학교  중학교  초등학교
0    건입동   1.0  0.0   1.0
1    구좌읍   1.0  2.0   9.0
2    남원읍   0.0  2.0   7.0
3    노형동   2.0  2.0   5.0
4    대륜동   1.0  0.0   3.0
5    대정읍   6.0  4.0   6.0
6    대천동   0.0  1.0   2.0
7    도두동   0.0  0.0   1.0
8    동홍동   2.0  2.0   1.0
9    봉개동   1.0  0.0   1.0
10  삼도1동   0.0  0.0   1.0
11  삼도2동   0.0  1.0   2.0
12   삼양동   0.0  1.0   2.0
13   서홍동   0.0  1.0   2.0
14   성산읍   1.0  2.0   7.0
15   송산동   0.0  0.0   2.0
16   아라동   4.0  4.0   2.0
17   안덕면   0.0  1.0   5.0
18   애월읍   2.0  3.0  11.0
19    연동   1.0  2.0   2.0
20   영천동   2.0  0.0   1.0
21   예래동   0.0  0.0   1.0
22   오라동   1.0  0.0   1.0
23   외도동   0.0  0.0   2.0
24  용담1동   0.0  1.0   1.0
25  용담2동   1.0  1.0   1.0
26   우도면   0.0  1.0   1.0
27  이도1동   0.0  0.0   2.0
28  이도2동   1.0  2.0   3.0
29  일도2동   0.0  0.0   3.0
30   정방동   0.0  1.0   0.0
31   조천읍   1.0  2.0   8.0
32   중문동   1.0  1.0   2.0
33   중앙동   0.0  0.0   1.0
34   추자면   0.0  1.0   2.0
35   표선면   1.0  1.0   5.0
36   한경면   1.0  3.0   3.0
37   한림읍   2.0  2.0   5.0
38   화북동   1.0  2.0   4.0
39   효돈동   0.0  1.0   1.0

In [20]:
df['초등학교수']=0
df['중학교수']=0
df['고등학교수']=0
df

,날짜,연,월,행정시,행정동,사업체수,세대수,세대당 인구,남여 비율,단독주택,...,동.식물관련시설,숙박시설,교육연구시설,관광휴게시설,분뇨.쓰레기처리시설,건설이후(일),건설이후(일)_std,초등학교수,중학교수,고등학교수
0,2018-01-01,2018,1,제주시,건입동,849,4324,2.27,1.08,219,...,0,11,1,0,0,10697.0,5011.0,0,0,0
1,2018-01-01,2018,1,제주시,구좌읍,"2,016",7493,2.08,1.05,4104,...,344,31,31,0,3,14289.0,8577.0,0,0,0
2,2018-01-01,2018,1,서귀포시,남원읍,"1,394",8345,2.29,1.05,5689,...,468,169,29,0,10,9737.0,5979.0,0,0,0
3,2018-01-01,2018,1,제주시,노형동,"5,028",20455,2.61,0.97,671,...,36,58,25,1,1,6155.0,4172.0,0,0,0
4,2018-01-01,2018,1,서귀포시,대륜동,964,5586,2.41,1.03,1973,...,20,68,31,0,5,10172.0,9211.0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57572,2021-08-31,2021,8,서귀포시,표선면,"1,381",6175,2.00,1.04,3848,...,467,125,48,1,9,8906.0,7151.0,0,0,0
57573,2021-08-31,2021,8,제주시,한경면,899,4938,1.87,1.01,2680,...,197,4,20,0,2,15084.0,9407.0,0,0,0
57574,2021-08-31,2021,8,제주시,한림읍,"2,521",10546,2.01,1.06,1958,...,723,83,28,6,15,9980.0,8644.0,0,0,0
57575,2021-08-31,2021,8,제주시,화북동,"1,947",9691,2.50,0.99,308,...,6,0,14,0,1,8003.0,5578.0,0,0,0
57576,2021-08-31,2021,8,서귀포시,효돈동,355,2324,2.27,1.02,1353,...,3,5,12,0,0,12578.0,8205.0,0,0,0

In [21]:
for i in range(len(df)):
    for j in range(len(행정동별_학교급수_df)):
        if df.loc[i, '행정동']==행정동별_학교급수_df.loc[j, '행정동명']:
            df.loc[i, '초등학교수']= 행정동별_학교급수_df.loc[j,'초등학교']
            df.loc[i, '중학교수']= 행정동별_학교급수_df.loc[j,'중학교']
            df.loc[i, '고등학교수']= 행정동별_학교급수_df.loc[j,'고등학교']
df

,날짜,연,월,행정시,행정동,사업체수,세대수,세대당 인구,남여 비율,단독주택,...,동.식물관련시설,숙박시설,교육연구시설,관광휴게시설,분뇨.쓰레기처리시설,건설이후(일),건설이후(일)_std,초등학교수,중학교수,고등학교수
0,2018-01-01,2018,1,제주시,건입동,849,4324,2.27,1.08,219,...,0,11,1,0,0,10697.0,5011.0,1.0,0.0,1.0
1,2018-01-01,2018,1,제주시,구좌읍,"2,016",7493,2.08,1.05,4104,...,344,31,31,0,3,14289.0,8577.0,9.0,2.0,1.0
2,2018-01-01,2018,1,서귀포시,남원읍,"1,394",8345,2.29,1.05,5689,...,468,169,29,0,10,9737.0,5979.0,7.0,2.0,0.0
3,2018-01-01,2018,1,제주시,노형동,"5,028",20455,2.61,0.97,671,...,36,58,25,1,1,6155.0,4172.0,5.0,2.0,2.0
4,2018-01-01,2018,1,서귀포시,대륜동,964,5586,2.41,1.03,1973,...,20,68,31,0,5,10172.0,9211.0,3.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57572,2021-08-31,2021,8,서귀포시,표선면,"1,381",6175,2.00,1.04,3848,...,467,125,48,1,9,8906.0,7151.0,5.0,1.0,1.0
57573,2021-08-31,2021,8,제주시,한경면,899,4938,1.87,1.01,2680,...,197,4,20,0,2,15084.0,9407.0,3.0,3.0,1.0
57574,2021-08-31,2021,8,제주시,한림읍,"2,521",10546,2.01,1.06,1958,...,723,83,28,6,15,9980.0,8644.0,5.0,2.0,2.0
57575,2021-08-31,2021,8,제주시,화북동,"1,947",9691,2.50,0.99,308,...,6,0,14,0,1,8003.0,5578.0,4.0,2.0,1.0
57576,2021-08-31,2021,8,서귀포시,효돈동,355,2324,2.27,1.02,1353,...,3,5,12,0,0,12578.0,8205.0,1.0,1.0,0.0

In [22]:
"""
월별_행정동별_세대수 -> 0
행정동별_건설이후(일) -> 0
행정동별_사업자수(2019) -> 0
행정동별_주택종류 -> 0
행정동별_학교급수 -> 0
"""

'\n월별_행정동별_세대수 -> 0\n행정동별_건설이후(일) -> 0\n행정동별_사업자수(2019) -> 0\n행정동별_주택종류 -> 0\n행정동별_학교급수 -> 0\n'

In [23]:
df.to_csv("전처리/전처리_완료(나연).csv", encoding="cp949")

In [24]:
df.columns

Index(['날짜', '연', '월', '행정시', '행정동', '사업체수', '세대수', '세대당 인구', '남여 비율', '단독주택',
       '창고시설', '제2종근린생활시설', '제1종근린생활시설', '공동주택', '동.식물관련시설', '숙박시설', '교육연구시설',
       '관광휴게시설', '분뇨.쓰레기처리시설', '건설이후(일)', '건설이후(일)_std', '초등학교수', '중학교수',
       '고등학교수'],
      dtype='object')

In [25]:
전처리_df=pd.read_csv("전처리/전처리_완료(나연).csv", encoding="cp949")
전처리_df

,Unnamed: 0,날짜,연,월,행정시,행정동,사업체수,세대수,세대당 인구,남여 비율,...,동.식물관련시설,숙박시설,교육연구시설,관광휴게시설,분뇨.쓰레기처리시설,건설이후(일),건설이후(일)_std,초등학교수,중학교수,고등학교수
0,0,2018-01-01,2018,1,제주시,건입동,849,4324,2.27,1.08,...,0,11,1,0,0,10697.0,5011.0,1.0,0.0,1.0
1,1,2018-01-01,2018,1,제주시,구좌읍,"2,016",7493,2.08,1.05,...,344,31,31,0,3,14289.0,8577.0,9.0,2.0,1.0
2,2,2018-01-01,2018,1,서귀포시,남원읍,"1,394",8345,2.29,1.05,...,468,169,29,0,10,9737.0,5979.0,7.0,2.0,0.0
3,3,2018-01-01,2018,1,제주시,노형동,"5,028",20455,2.61,0.97,...,36,58,25,1,1,6155.0,4172.0,5.0,2.0,2.0
4,4,2018-01-01,2018,1,서귀포시,대륜동,964,5586,2.41,1.03,...,20,68,31,0,5,10172.0,9211.0,3.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57572,57572,2021-08-31,2021,8,서귀포시,표선면,"1,381",6175,2.00,1.04,...,467,125,48,1,9,8906.0,7151.0,5.0,1.0,1.0
57573,57573,2021-08-31,2021,8,제주시,한경면,899,4938,1.87,1.01,...,197,4,20,0,2,15084.0,9407.0,3.0,3.0,1.0
57574,57574,2021-08-31,2021,8,제주시,한림읍,"2,521",10546,2.01,1.06,...,723,83,28,6,15,9980.0,8644.0,5.0,2.0,2.0
57575,57575,2021-08-31,2021,8,제주시,화북동,"1,947",9691,2.50,0.99,...,6,0,14,0,1,8003.0,5578.0,4.0,2.0,1.0
57576,57576,2021-08-31,2021,8,서귀포시,효돈동,355,2324,2.27,1.02,...,3,5,12,0,0,12578.0,8205.0,1.0,1.0,0.0

In [26]:
now  = datetime.now()
date=pd.to_datetime(전처리_df.loc[0,'날짜'])
date_diff = now - date
print(date_diff.days)

1344

In [27]:
now  = datetime.now()
for i in range(len(전처리_df)):
    date=pd.to_datetime(전처리_df.loc[i,'날짜'])
    date_diff = now - date
    전처리_df.loc[i,'건설이후(일)']-=date_diff.days
    
전처리_df

,Unnamed: 0,날짜,연,월,행정시,행정동,사업체수,세대수,세대당 인구,남여 비율,...,동.식물관련시설,숙박시설,교육연구시설,관광휴게시설,분뇨.쓰레기처리시설,건설이후(일),건설이후(일)_std,초등학교수,중학교수,고등학교수
0,0,2018-01-01,2018,1,제주시,건입동,849,4324,2.27,1.08,...,0,11,1,0,0,9353.0,5011.0,1.0,0.0,1.0
1,1,2018-01-01,2018,1,제주시,구좌읍,"2,016",7493,2.08,1.05,...,344,31,31,0,3,12945.0,8577.0,9.0,2.0,1.0
2,2,2018-01-01,2018,1,서귀포시,남원읍,"1,394",8345,2.29,1.05,...,468,169,29,0,10,8393.0,5979.0,7.0,2.0,0.0
3,3,2018-01-01,2018,1,제주시,노형동,"5,028",20455,2.61,0.97,...,36,58,25,1,1,4811.0,4172.0,5.0,2.0,2.0
4,4,2018-01-01,2018,1,서귀포시,대륜동,964,5586,2.41,1.03,...,20,68,31,0,5,8828.0,9211.0,3.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57572,57572,2021-08-31,2021,8,서귀포시,표선면,"1,381",6175,2.00,1.04,...,467,125,48,1,9,8900.0,7151.0,5.0,1.0,1.0
57573,57573,2021-08-31,2021,8,제주시,한경면,899,4938,1.87,1.01,...,197,4,20,0,2,15078.0,9407.0,3.0,3.0,1.0
57574,57574,2021-08-31,2021,8,제주시,한림읍,"2,521",10546,2.01,1.06,...,723,83,28,6,15,9974.0,8644.0,5.0,2.0,2.0
57575,57575,2021-08-31,2021,8,제주시,화북동,"1,947",9691,2.50,0.99,...,6,0,14,0,1,7997.0,5578.0,4.0,2.0,1.0
57576,57576,2021-08-31,2021,8,서귀포시,효돈동,355,2324,2.27,1.02,...,3,5,12,0,0,12572.0,8205.0,1.0,1.0,0.0

In [28]:
전처리_df.to_csv("전처리/전처리_완료(나연).csv", encoding="cp949")

In [29]:
dfdf=pd.read_csv("전처리/전처리_완료(나연).csv", encoding="cp949")
dfdf

,Unnamed: 0,Unnamed: 0.1,날짜,연,월,행정시,행정동,사업체수,세대수,세대당 인구,...,동.식물관련시설,숙박시설,교육연구시설,관광휴게시설,분뇨.쓰레기처리시설,건설이후(일),건설이후(일)_std,초등학교수,중학교수,고등학교수
0,0,0,2018-01-01,2018,1,제주시,건입동,849,4324,2.27,...,0,11,1,0,0,9353.0,5011.0,1.0,0.0,1.0
1,1,1,2018-01-01,2018,1,제주시,구좌읍,"2,016",7493,2.08,...,344,31,31,0,3,12945.0,8577.0,9.0,2.0,1.0
2,2,2,2018-01-01,2018,1,서귀포시,남원읍,"1,394",8345,2.29,...,468,169,29,0,10,8393.0,5979.0,7.0,2.0,0.0
3,3,3,2018-01-01,2018,1,제주시,노형동,"5,028",20455,2.61,...,36,58,25,1,1,4811.0,4172.0,5.0,2.0,2.0
4,4,4,2018-01-01,2018,1,서귀포시,대륜동,964,5586,2.41,...,20,68,31,0,5,8828.0,9211.0,3.0,0.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
57572,57572,57572,2021-08-31,2021,8,서귀포시,표선면,"1,381",6175,2.00,...,467,125,48,1,9,8900.0,7151.0,5.0,1.0,1.0
57573,57573,57573,2021-08-31,2021,8,제주시,한경면,899,4938,1.87,...,197,4,20,0,2,15078.0,9407.0,3.0,3.0,1.0
57574,57574,57574,2021-08-31,2021,8,제주시,한림읍,"2,521",10546,2.01,...,723,83,28,6,15,9974.0,8644.0,5.0,2.0,2.0
57575,57575,57575,2021-08-31,2021,8,제주시,화북동,"1,947",9691,2.50,...,6,0,14,0,1,7997.0,5578.0,4.0,2.0,1.0
57576,57576,57576,2021-08-31,2021,8,서귀포시,효돈동,355,2324,2.27,...,3,5,12,0,0,12572.0,8205.0,1.0,1.0,0.0